### ISSUE TITLE
guitarsniffer not starting

### ISSUE THREAD

**Issue by RJPercival** [artman41/guitarsniffer#1]
I've found that when using winpcap from the download link in README.md, guitarsniffer doesn't even appear to start. If I install npcap install (with winpcap API compatibility enabled), guitarsniffer does start but doesn't display any button presses, nor does it display any packets.

I have a Guitar Hero Live for Xbox One controller connected to the PC. I'm using Windows 10.

**Comment by RJPercival** [comment]
Since the version from the releases page wasn't printing anything to the console, I've compiled it myself and here is the output:
```
C:>go get github.com/artman41/guitarsniffer/cmd/guitarsniffer

C:>guitarsniffer
2019/05/22 22:36:48 Warning: untested vJoy version: 536 != 516
Getting Joypad...
Obtained!
Starting Sniffer...
```

**Comment by RJPercival** [comment]
I think I've found the problem. The following line always returns the error "Timeout Expired":
https://github.com/artman41/guitarsniffer/blob/2337ce98f9e36cdda0b7e5964ca98bf470404810/guitarsniffer/guitarsniffer.go#L61

**Comment by RJPercival** [comment]
It appears to be selecting the wrong device. With winpcap installed, my device list is as follows:
```
{\Device\NPF_{2DE66103-040F-4432-...} Microsoft 0 [{fe80::64db:a44c:... <nil> <nil> <nil>} {192.168.0.12 ffffff00 255.255.255.255 <nil>}]}
{\Device\NPF_{9AB8EF12-6542-4D62-...} TAP-Windows Adapter V9 0 [{fe80::9919:2c02:... <nil> <nil> <nil>} {fe80::9919:2c02:... <nil> <nil> <nil>}]}
{\Device\NPF_{A76D6929-D098-4387-...} Microsoft 0 [{fe80::d98f:1238:... <nil> <nil> <nil>} {fe80::d98f:1238:... <nil> <nil> <nil>}]}
{\Device\NPF_{90F87117-B084-4C2C-...} Intel(R) Ethernet Connection (2) I219-V 0 [{fe80::8c33:cbe2:... <nil> <nil> <nil>} {192.168.0.45 ffffff00 255.255.255.255 <nil>}]}
```

I noticed [a post on Reddit](https://www.reddit.com/r/CloneHero/comments/8bv7y5/heres_the_current_working_version_of_the_xbone/e2gx0v2?utm_source=share&utm_medium=web2x) talking about the "new slimline adapter", which I suspect I have - I guess this isn't supported? In which case, updating the README to mention that is probably a good idea.

**Comment by artman41** [comment]
@RJPercival I'm afraid you may be correct, I don't own the slimline adapter - only the older fat adapter

I believe that this is the new adapter
![slimeline](https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/225787-L-LO.jpg)

Whereas this is the fat adapter
![fat](https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSaz8pJ-z9AKf5ngSGueOTqe2dm-WzqfKjyhTDp27BL1rMmm_4zQJIvsXjJAatyXQ_eE0pKLNsaz613RRVpVCmO09IZVWaydJPTcPoKMM0sjOv0NZUgjBZ0_w&usqp=CAY)


What I can do however is, using that device list you gave me, create a custom version for you

If we can get that to work then I'll merge it into the main branch for everyone to use 👍

**Comment by RJPercival** [comment]
Thanks, that'd be great. Which of the listed devices do you think is the adapter? Mine actually doesn't look like either of those pictures - it's more rounded with the light on the end, like this:
![](https://b68multimedia.co.uk/wp-content/uploads/imported/0/Official-MicrosoftXbox-One-Official-GUITAR-HERO-LIVE-Replacement-USB-Dongle-272861630800.JPG)

**Comment by artman41** [comment]
@RJPercival I feel like your device is `{\Device\NPF_{9AB8EF12-6542-4D62-...} TAP-Windows Adapter V9 0 [{fe80::9919:2c02:... <nil> <nil> <nil>} {fe80::9919:2c02:... <nil> <nil> <nil>}]}`

If you wouldn't mind, I'd like a you to get the device list with your adapter both plugged in and not plugged in your system

we'll definitely know which one it is then :+1:

**Comment by ShiningDown** [comment]
the adapter the guy has is the Guitar Hero Live one.

the slim xbox one adapter works with this tool, as I have it.

**Comment by artman41** [comment]
Closing due to lack of interaction from the submitter

If anyone wants to revive this, make a new issue and reference this one 👍
