### ISSUE TITLE
Anyway around vJoy?

### ISSUE THREAD

**Issue by frankzappa117** [artman41/guitarsniffer#2]
It looks like Windows 1903 killed vJoy and the project is no longer supported. Anyway around it? Since it fails to install there is no way the sniffer actually recognizes the keystrokes

**Comment by artman41** [comment]
@frankzappa117 Thanks for bringing this to my attention, I didn't actually know 1903 killed vJoy

For now there's no ways around it since I've not heard of the issue before

I'll look into some projects similar to vJoy and see if I can use them in the same way

**Comment by artman41** [comment]
Looks like there's a fork of Vjoy now so no need to worry

@frankzappa117 install this one instead and it should work fine 👍 

https://github.com/jshafer817/vJoy/releases
